# Use postgres/example user/password credentials
#version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
# docker network create mynet
# docker run -d --name db --restart=always -e POSTGRES_PASSWORD=password postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#docker run -d --name adminer --restart=always -p 8080:8080 adminer
